adding a check for the required variables

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,6 +46,11 @@ jobs:
           dotnet-gitversion /output json > gitversion.json || (echo "GitVersion failed:"; cat gitversion.json || true; exit 1)
           cat gitversion.json
           echo "version=$(jq -r .SemVer gitversion.json)" >> $GITHUB_OUTPUT
+      - name: Check required environment variables
+        run: |
+          if [ -z "${{ secrets.PACKAGES_API_KEY }}" ]; then echo "PACKAGES_API_KEY is missing!"; exit 1; fi
+          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then echo "GITHUB_TOKEN is missing!"; exit 1; fi
+          if [ -z "${{ steps.gitversion.outputs.version }}" ]; then echo "GITVERSION_NUGET_VERSION is missing!"; exit 1; fi
       - name: 'Run: Publish'
         run: ./build.cmd Publish --host GitHubActions
         env:
